spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: all
  datasource:
    name: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  packages-to-scan: ru.mirea
  paths-to-match: /api/**